sudo: required
services:
  -docker

before_install:
  - docker build -t davidchow/docker-vue-ci -f Dockerfile.dev .

script:
  - docker run davidchow/docker-vue-ci npm run test:unit

deploy:
  provider: elasticbeanstalk
  region: "ap-southeast-2"
  app: "docker_vue"
  env: "Dockervue-env"
  bucket_name: "elasticbeanstalk-ap-southeast-2-674117693681"
  bucket_path: "docker_vue"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_ACCESS_SECRET

