version: "3"
services:
    web:
        build: 
            context: .
            dockerfile: Dockerfile.dev
        ports:
            - "8080:8080"
        volumes: 
            - ./src:/app/src
            - ./public:/app/public
        command: ["npm", "run", "serve"]


            